# Generated by Django 4.2 on 2023-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayısı'),
        ),
    ]
