# Generated by Django 4.2 on 2023-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='Renk'),
        ),
    ]
